-- === EMPLOYEE ===
CREATE TABLE employee (
    emp_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR2(50)  NOT NULL,
    last_name     VARCHAR2(50)  NOT NULL,
    email         VARCHAR2(100) NOT NULL UNIQUE,
    doj           DATE          NOT NULL,
    dept_code     VARCHAR2(20)
);
