-- === LEAVE_TYPE ===
CREATE TABLE leave_type (
    type_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name      VARCHAR2(30)  NOT NULL UNIQUE,
    max_days_annual NUMBER(3)    NOT NULL
);