-- === LEAVE_REQUEST ===
CREATE TABLE leave_request (
    req_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id        NUMBER  NOT NULL,
    type_id       NUMBER  NOT NULL,
    start_date    DATE    NOT NULL,
    end_date      DATE    NOT NULL,
    status        VARCHAR2(20) DEFAULT 'PENDING', -- PENDING / APPROVED / REJECTED / CANCELLED
    approver_id   NUMBER,
    requested_on  DATE    DEFAULT SYSDATE,
    CONSTRAINT fk_lr_emp      FOREIGN KEY (emp_id)      REFERENCES employee(emp_id),
    CONSTRAINT fk_lr_type     FOREIGN KEY (type_id)     REFERENCES leave_type(type_id),
    CONSTRAINT fk_lr_approver FOREIGN KEY (approver_id) REFERENCES employee(emp_id)
);
