-- === HOLIDAY ===
CREATE TABLE holiday (
    holi_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holi_date      DATE        NOT NULL,
    description    VARCHAR2(100) NOT NULL,
    country_code   CHAR(2)     NOT NULL
);

