-- === PAYROLL_ADJ ===
CREATE TABLE payroll_adj (
    adj_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id     NUMBER  NOT NULL,
    adj_date   DATE    DEFAULT TRUNC(SYSDATE),
    amount     NUMBER(10,2) NOT NULL,
    reason     VARCHAR2(200),
    posted_by  NUMBER  NOT NULL,
    CONSTRAINT fk_pa_emp FOREIGN KEY (emp_id)    REFERENCES employee(emp_id),
    CONSTRAINT fk_pa_hr  FOREIGN KEY (posted_by) REFERENCES employee(emp_id)
);
