-- === APP_USER ===
CREATE TABLE app_user (
    user_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_name  VARCHAR2(50) NOT NULL UNIQUE,
    pwd_hash    VARCHAR2(200) NOT NULL,
    emp_id      NUMBER,
    active_flag CHAR(1) DEFAULT 'Y',
    CONSTRAINT fk_au_emp FOREIGN KEY (emp_id) REFERENCES employee(emp_id)
);