-- === EMPLOYEE ===
CREATE TABLE employee (
    emp_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR2(50)  NOT NULL,
    last_name     VARCHAR2(50)  NOT NULL,
    email         VARCHAR2(100) NOT NULL UNIQUE,
    doj           DATE          NOT NULL,
    dept_code     VARCHAR2(20)
);

-- === LEAVE_TYPE ===
CREATE TABLE leave_type (
    type_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name      VARCHAR2(30)  NOT NULL UNIQUE,
    max_days_annual NUMBER(3)    NOT NULL
);

-- === LEAVE_REQUEST ===
CREATE TABLE leave_request (
    req_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id        NUMBER  NOT NULL,
    type_id       NUMBER  NOT NULL,
    start_date    DATE    NOT NULL,
    end_date      DATE    NOT NULL,
    status        VARCHAR2(20) DEFAULT 'PENDING', -- PENDING / APPROVED / REJECTED / CANCELLED
    approver_id   NUMBER,
    requested_on  DATE    DEFAULT SYSDATE,
    CONSTRAINT fk_lr_emp      FOREIGN KEY (emp_id)      REFERENCES employee(emp_id),
    CONSTRAINT fk_lr_type     FOREIGN KEY (type_id)     REFERENCES leave_type(type_id),
    CONSTRAINT fk_lr_approver FOREIGN KEY (approver_id) REFERENCES employee(emp_id)
);

-- === HOLIDAY ===
CREATE TABLE holiday (
    holi_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holi_date      DATE        NOT NULL,
    description    VARCHAR2(100) NOT NULL,
    country_code   CHAR(2)     NOT NULL
);

-- === PAYROLL_ADJ ===
CREATE TABLE payroll_adj (
    adj_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id     NUMBER  NOT NULL,
    adj_date   DATE    DEFAULT TRUNC(SYSDATE),
    amount     NUMBER(10,2) NOT NULL,
    reason     VARCHAR2(200),
    posted_by  NUMBER  NOT NULL,
    CONSTRAINT fk_pa_emp FOREIGN KEY (emp_id)    REFERENCES employee(emp_id),
    CONSTRAINT fk_pa_hr  FOREIGN KEY (posted_by) REFERENCES employee(emp_id)
);

-- === APP_ROLE ===
CREATE TABLE app_role (
    role_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name   VARCHAR2(30) NOT NULL UNIQUE
);

-- === APP_USER ===
CREATE TABLE app_user (
    user_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_name  VARCHAR2(50) NOT NULL UNIQUE,
    pwd_hash    VARCHAR2(200) NOT NULL,
    emp_id      NUMBER,
    active_flag CHAR(1) DEFAULT 'Y',
    CONSTRAINT fk_au_emp FOREIGN KEY (emp_id) REFERENCES employee(emp_id)
);

-- === APP_USER_ROLE ===
CREATE TABLE app_user_role (
    user_id    NUMBER NOT NULL,
    role_id    NUMBER NOT NULL,
    granted_on DATE   DEFAULT SYSDATE,
    CONSTRAINT pk_user_role PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES app_user(user_id),
    CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES app_role(role_id)
);
