-- === EMPLOYEE ===
CREATE TABLE employee (
    emp_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR2(50)  NOT NULL,
    last_name     VARCHAR2(50)  NOT NULL,
    email         VARCHAR2(100) NOT NULL UNIQUE,
    doj           DATE          NOT NULL,
    dept_code     VARCHAR2(20)
);

-- === LEAVE_TYPE ===
CREATE TABLE leave_type (
    type_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name      VARCHAR2(30)  NOT NULL UNIQUE,
    max_days_annual NUMBER(3)    NOT NULL
);
